### ISSUE TITLE
The sandbox script is not compatible with the current version of Uranium.

### ISSUE THREAD

**Issue by GreenGremlin** [toumorokoshi/sprinter#63]
It would be nice if scripts/sandbox.sh would install a standalone copy of the version of Uranium it needs, if that's possible. If that is not possible, the documentation should be updated with instructions for doing so manually.

Currently, running `pip install uranium` and executing sandbox.sh fails with the following output:

```
$curl -s https://raw.githubusercontent.com/toumorokoshi/sprinter/master/scripts/sandbox.sh > /tmp/sprinter; bash /tmp/sprinter
override r-xr-xr-x  jonathan/wheel for /tmp/sprinter-sandbox/.uranium/.Python? y
override r-xr-xr-x  jonathan/wheel for /tmp/sprinter-sandbox/.uranium/lib/python2.7/config/libpython2.7.a? y
override r-xr-xr-x  jonathan/wheel for /tmp/sprinter-sandbox/.uranium/lib/python2.7/config/libpython2.7.dylib? y
Creating sandbox directory...
Downloading sprinter...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0   136    0     0     33      0 --:--:--  0:00:04 --:--:--    53
  0     0    0 79625    0     0  16575      0 --:--:--  0:00:04 --:--:--  267k
Creating python sandbox...
installing virtualenv...
Downloading url: https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.0.tar.gz
extracting to /var/folders/z9/9r6rn9r51t52fmq98xc1fzvr0000gp/T/tmpJn4iHs...
Using real prefix '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7'
New python executable in /private/tmp/sprinter-sandbox/.uranium/bin/python
Please make sure you remove any previous custom paths from your /Users/jonathan/.pydistutils.cfg file.
Installing setuptools, pip, wheel...done.
setting up uranium...
Traceback (most recent call last):
  File "./uranium", line 227, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./uranium", line 73, in main
    version=options.version)
  File "./uranium", line 149, in _install_uranium
    '--upgrade'], stdout=fh, stderr=fh)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
!!
Failure with prebuild!
```

**Comment by toumorokoshi** [comment]
Hi @xgecko this is fixed now. can you give it a try?

**Comment by xgecko** [comment]
It's still failing for me, with the same error. After running `pip install uranium`, which seems to succeed, I have ~/bin/uranium, but `pip list` does not list uranium and `pip uninstall uranium` fails "Cannot uninstall requirement uranium, not installed".

**Comment by toumorokoshi** [comment]
that's more of a python with pip (sounds like it's installed on the user but not system and pip is getting confused).

Can you remove that /tmp/sprinter script and try again? I had to do that when I tried it.

**Comment by xgecko** [comment]
Tried `rm -r /tmp/sprinter*` and running sandbox.sh again, got the same error. It doesn't look like pip is installed in the uranium virtual environment.

```
$ls /tmp/sprinter-sandbox/.uranium/bin/
activate         activate.csh     activate.fish    activate_this.py python           python2          python2.7
```

**Comment by toumorokoshi** [comment]
@GreenGremlin is this fixed for you too? re toumorokoshi/sprinter#9?

**Comment by GreenGremlin** [comment]
Yes, it is. Thanks!

**Comment by GreenGremlin** [comment]
Here's a PR documenting the workaround and adding a symlink formula.

https://github.com/toumorokoshi/sprinter/pull/65
